<?xml version="1.0"?>

<robot name="properties" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.1415926535897931"/>
  
  <xacro:property name="base_dim_X" value="0.6"/>
  <xacro:property name="base_dim_Y" value="0.3"/>
  <xacro:property name="base_dim_Z" value="0.1"/>
  <xacro:property name="base_mass" value="20"/>

  <xacro:property name="laser_dim_X" value="0.07"/>
  <xacro:property name="laser_dim_Y" value="0.1"/>
  <xacro:property name="laser_dim_Z" value="0.07"/>

  <xacro:property name="wheel_width" value="0.05"/>
  <xacro:property name="wheel_radius" value="0.07"/>
  <xacro:property name="wheel_dist" value="${(wheel_width/10)}"/>
  <xacro:property name="wheel_pos_X" value="${(base_dim_X/2) - wheel_radius}"/>
  <xacro:property name="wheel_pos_Z" value="${(wheel_width)*-1}"/>
  <xacro:property name="wheel_mass" value="5"/>

  <xacro:property name="caster_dim_X" value="0.05"/>
  <xacro:property name="caster_dim_Y" value="0.05"/>
  <xacro:property name="caster_dim_Z" value="0.1"/>
  <xacro:property name="caster_mass" value="1"/>

  <xacro:property name="wheel_caster_lenght" value="0.05"/>
  <xacro:property name="wheel_caster_radius" value="0.03"/>
  <xacro:property name="wheel_caster_mass" value="1"/>

</robot>