<?xml version="1.0"?>

<robot name="wheel" xmlns:xacro="http://www.ros.org/wiki/xacro">
      <xacro:macro name="wheel" params="lr tY">
       <link name="${lr}_wheel_link">
        <collision>
          <origin xyz="0 0 0" rpy="0 ${PI/2} ${(-PI/2)*tY}" />
          <geometry>
              <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 0" rpy="0 ${PI/2} ${(-PI/2)*tY}" />
          <geometry>
              <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
          </geometry>
        </visual>

        <inertial>
          <origin xyz="0 0 0" rpy="0 ${PI/2} ${(-PI/2)*tY}" />
          <mass value="${wheel_mass}"/>
          <cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
        </inertial>
       </link>

        <!--<gazebo reference="${lr}_wheel">
          <mu1 value="1.0"/>
          <mu2 value="1.0"/>
          <kp  value="10000000.0" />
          <kd  value="1.0" />
          <fdir1 value="1 0 0"/>
          <material>Gazebo/Black</material>
        </gazebo>-->


       <joint name="${lr}_wheel_joint" type="continuous">
          <parent link="base_link"/>
          <child link="${lr}_wheel_link"/>
          <origin xyz="${wheel_pos_X} ${tY*((base_dim_Y/2) + (wheel_width/2)+ wheel_dist)} ${wheel_pos_Z}" rpy="0 0 0" /> 
          <axis xyz="0 1 0" rpy="0 0 0" />
          <limit effort="100" velocity="100"/>
          <joint_properties damping="0.0" friction="0.0"/>
        </joint>


      <!--<transmission name="${lr}_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="${lr}_wheel_hinge"/>
        <actuator name="${lr}Motor">
          <hardwareInterface>EffortJointInterface</hardwareInterface>
          <mechanicalReduction>10</mechanicalReduction>
        </actuator>
      </transmission>-->
     </xacro:macro>

</robot>