<?xml version="1.0" encoding="utf-8"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="differentialRobot_v003">

 <xacro:include filename="$(find robot_description)/urdf/differential/differentialRobot_v003/xacro_include/wheel.xacro" />
 <xacro:include filename="$(find robot_description)/urdf/differential/differentialRobot_v003/xacro_include/inertia.xacro" />
 <xacro:include filename="$(find robot_description)/urdf/differential/differentialRobot_v003/xacro_include/caster.xacro" />
 <xacro:include filename="$(find robot_description)/urdf/differential/differentialRobot_v003/xacro_include/base.xacro" />
 <xacro:include filename="$(find robot_description)/urdf/differential/differentialRobot_v003/xacro_include/laser.xacro" />
 <xacro:include filename="$(find robot_description)/urdf/differential/differentialRobot_v003/xacro_include/properties.xacro" />
 <xacro:include filename="$(find robot_description)/urdf/differential/differentialRobot_v003/xacro_include/gazebo_colors.xacro" />

 <xacro:base/>
 <xacro:wheel lr="left" tY="1"/>
 <xacro:wheel lr="right" tY="-1"/>
 <xacro:caster/>
 <xacro:laser/>

 <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <leftJoint>left_wheel_joint</leftJoint>
      <rightJoint>right_wheel_joint</rightJoint>
      <robotBaseFrame>base_link</robotBaseFrame>
      <wheelSeparation>${wheel_width + base_dim_Y}</wheelSeparation>
      <wheelDiameter>${wheel_radius*2}</wheelDiameter>
      <publishWheelJointState>true</publishWheelJointState>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <jointName>caster_joint, wheel_caster_joint</jointName>
    </plugin>
  </gazebo>

</robot>